function testToolbox(varargin)
% testToolbox - Run the ndi-ontology-matlab test suite using MatBox.
    projectRootDir = nditools.projectdir();
    matbox.tasks.testToolbox(projectRootDir, ...
        "SourceFolderName", "src", ...
        "TestsFolderName", "tests", ...
        "Verbosity", "Terse", ...
        varargin{:})
end
