% Location: fullfile(ndi.common.PathConstants.RootFolder,'test','+ndi','+unittest','+ontology','TestOntologyLookup.m')

classdef TestOntologyLookup < matlab.unittest.TestCase
    % TestOntologyLookup - Unit tests for the main ndi.ontology.lookup function.
    %
    %   Uses TestParameterDefinition methods to load test cases from JSON.
    %
    %   Requires an active internet connection to query external APIs.

    properties (TestParameter)
        % Define the testCases parameter - its values will be generated by initializeTestCases
        testCases
    end

    methods (Static, TestParameterDefinition)
        % This method generates the values for the 'testCases' TestParameter
        function testCases = initializeTestCases()
            % Call the static loading function using the fully qualified name
            % Inside a method, this resolution should be reliable.
             try
                 testCases = ndi.unittest.ontology.TestOntologyLookup.loadOntologyTestCases();
             catch ME
                 % Throw a specific error if loading fails during parameter generation
                 error('TestOntologyLookup:ParameterGenerationFailed', ...
                       'Failed to generate test parameters by loading JSON: %s', ME.message);
             end
        end
    end

    methods (Test)
        % The main test method, parameterized by testCases.
        function testLookupFunctionality(testCase, testCases)
            pause(1);
            % testCases here refers to a single element (a struct) from the testCases cell array for each iteration.

            lookupStr = testCases.lookup_string;
            shouldSucceed = testCases.should_succeed;
            expectedID = testCases.expected_id;
            expectedName = testCases.expected_name;
            expectedErrorId = '';
            if isfield(testCases, 'expected_error_id')
                expectedErrorId = testCases.expected_error_id;
            end

            % Create function handle for the call we want to test
            funcToTest = @() ndi.ontology.lookup(lookupStr);

            if shouldSucceed
                % Test Case: Expected to Succeed
                testCase.log(matlab.unittest.Verbosity.Detailed, sprintf('Testing SUCCESS case: "%s"', lookupStr));

                % Call directly (no try/catch). An unexpected exception must
                % surface with its full stack rather than being flattened into
                % a generic verifyFail message.
                [id, name, ~, ~, ~] = funcToTest();

                % Verify ID matches expected ID
                testCase.verifyEqual(id, expectedID, ...
                    sprintf('ID mismatch for successful lookup of "%s". Expected "%s", Got "%s".', ...
                            lookupStr, expectedID, id));

                % Verify Name matches expected Name (case-insensitive)
                testCase.verifyTrue(strcmpi(name, expectedName), ...
                    sprintf('Name mismatch for successful lookup of "%s". Expected "%s" (ignoring case), Got "%s".', ...
                            lookupStr, expectedName, name));

                % Fail-open guard: a lookup reported as successful MUST return a
                % non-empty id and name. This catches the fail-open bugs where a
                % lookup returned empty outputs with no exception.
                testCase.verifyNotEmpty(id, ...
                    sprintf('Successful lookup of "%s" returned an empty id (fail-open).', lookupStr));
                testCase.verifyNotEmpty(name, ...
                    sprintf('Successful lookup of "%s" returned an empty name (fail-open).', lookupStr));

            else
                % Test Case: Expected to Fail (throw an error)
                testCase.log(matlab.unittest.Verbosity.Detailed, sprintf('Testing FAILURE case: "%s"', lookupStr));

                caughtME = [];
                try
                    funcToTest();
                catch ME
                    caughtME = ME;
                end

                % Must have thrown something.
                testCase.verifyNotEmpty(caughtME, ...
                    sprintf('Expected an error for lookup of "%s", but none occurred.', lookupStr));

                % When a specific error identifier is pinned, require it to be
                % present in the thrown exception or anywhere in its cause chain.
                % ndi.ontology.lookup re-wraps subclass errors as
                % 'ndi:ontology:lookup:SpecificLookupError' (adding the original
                % as a cause), so a plain identifier check on the top-level
                % exception is not enough -- and an offline connection failure
                % must NOT satisfy a pinned not-found identifier.
                if ~isempty(caughtME) && ~isempty(expectedErrorId)
                    hasId = ndi.unittest.ontology.TestOntologyLookup.errorChainHasIdentifier(caughtME, expectedErrorId);
                    testCase.verifyTrue(hasId, ...
                        sprintf('Expected error id "%s" in the error/cause chain for "%s", but got "%s".', ...
                                expectedErrorId, lookupStr, caughtME.identifier));
                end
            end
        end
    end % methods (Test)

    methods (Static)
        function tf = errorChainHasIdentifier(ME, targetId)
            % ERRORCHAINHASIDENTIFIER - True if ME (or any cause, recursively)
            %   has identifier TARGETID. ndi.ontology.lookup re-wraps subclass
            %   errors and attaches the original as a cause, so the pinned
            %   identifier may live several levels down the cause chain.
            tf = false;
            if isempty(ME)
                return;
            end
            if strcmp(ME.identifier, targetId)
                tf = true;
                return;
            end
            causes = ME.cause;
            for k = 1:numel(causes)
                if ndi.unittest.ontology.TestOntologyLookup.errorChainHasIdentifier(causes{k}, targetId)
                    tf = true;
                    return;
                end
            end
        end % function errorChainHasIdentifier

        % Helper function to load test cases from JSON file.
        % Returns a CELL ARRAY of structs.
        function testCasesCellArray = loadOntologyTestCases()
            % Construct the file path using NDI path constants
            try
                currentDir = fileparts(mfilename('fullpath'));
                filePath = fullfile(currentDir, 'ontology_lookup_tests.json');
            catch ME
                 error('TestOntologyLookup:PathConstantError', ...
                       'Could not access ndi.common.PathConstants.RootFolder. Ensure NDI paths are set up correctly. Original error: %s', ME.message);
            end

            if ~exist(filePath, 'file')
                error('TestOntologyLookup:JSONNotFound', 'Test case JSON file not found: %s', filePath);
            end

            try
                jsonData = fileread(filePath);
                decodedData = jsondecode(jsonData);

                if isfield(decodedData, 'ontology_lookup_tests') && isstruct(decodedData.ontology_lookup_tests)
                     testCasesStructArray = decodedData.ontology_lookup_tests;
                     if isempty(testCasesStructArray)
                          error('TestOntologyLookup:JSONEmpty', 'Test case JSON file "%s" contains an empty "ontology_lookup_tests" array.', filePath);
                     end

                     % Convert struct array to cell array for TestParameter
                     numCases = numel(testCasesStructArray);
                     testCasesCellArray = cell(1, numCases);
                     for i = 1:numCases
                         testCasesCellArray{i} = testCasesStructArray(i);
                     end
                else
                    error('TestOntologyLookup:JSONFormatError', 'Test case JSON file "%s" does not contain the expected "ontology_lookup_tests" structure array field.', filePath);
                end

            catch ME
                 error('TestOntologyLookup:JSONError', 'Failed to load or decode test case JSON file "%s": %s', filePath, ME.message);
            end
        end
    end % methods (Static)

end % classdef


