classdef TestNCBITaxonOtherNames < matlab.unittest.TestCase
    % TestNCBITaxonOtherNames - Offline tests of the names NCBITaxon returns
    %   as synonyms, read from literal efetch records.
    %
    %   The parser this replaces read only <CommonName>, so a <Synonym> or a
    %   <GenbankCommonName> was never returned, and its loop over the
    %   <Name> entries searched the text of one <DispName> for <DispName>
    %   tags and so never returned anything. C. elegans, which has no
    %   common name, came back with no synonyms at all.

    methods (Test)

        function testFormerGenusIsASynonym(testCase)
            % NCBITaxon:6239, as efetch returns it
            xml = ['<TaxaSet><Taxon><TaxId>6239</TaxId>' ...
                '<ScientificName>Caenorhabditis elegans</ScientificName>' ...
                '<OtherNames>' ...
                '<Synonym>Rhabditis elegans</Synonym>' ...
                '<Name><ClassCDE>authority</ClassCDE>' ...
                '<DispName>Caenorhabditis elegans (Maupas, 1900)</DispName></Name>' ...
                '<Name><ClassCDE>authority</ClassCDE>' ...
                '<DispName>Rhabditis elegans Maupas, 1899</DispName></Name>' ...
                '</OtherNames></Taxon></TaxaSet>'];
            names = ndi.ontology.NCBITaxon.parseOtherNames(xml);
            testCase.verifyEqual(names, {'Rhabditis elegans'});
        end

        function testCommonNamesAndNotIncludesOrMisspellings(testCase)
            % NCBITaxon:10090, shortened
            xml = ['<OtherNames>' ...
                '<GenbankCommonName>house mouse</GenbankCommonName>' ...
                '<CommonName>mouse</CommonName>' ...
                '<Includes>nude mice</Includes>' ...
                '<Name><ClassCDE>authority</ClassCDE>' ...
                '<DispName>Mus musculus Linnaeus, 1758</DispName></Name>' ...
                '<Name><ClassCDE>misspelling</ClassCDE>' ...
                '<DispName>mice C57BL/6xCBA/CaJ hybrid</DispName></Name>' ...
                '</OtherNames>'];
            names = ndi.ontology.NCBITaxon.parseOtherNames(xml);
            testCase.verifyEqual(names, {'house mouse'; 'mouse'});
        end

        function testNameEntriesOfAKeptKind(testCase)
            xml = ['<OtherNames>' ...
                '<Name><ClassCDE>equivalent name</ClassCDE>' ...
                '<DispName>Escherichia coli &amp; relatives</DispName></Name>' ...
                '<Name><ClassCDE>synonym</ClassCDE>' ...
                '<DispName>Bacillus coli</DispName></Name>' ...
                '<Synonym>Bacillus coli</Synonym>' ...
                '</OtherNames>'];
            names = ndi.ontology.NCBITaxon.parseOtherNames(xml);
            testCase.verifyEqual(names, {'Bacillus coli'; 'Escherichia coli & relatives'});
        end

        function testNoOtherNames(testCase)
            testCase.verifyEqual(ndi.ontology.NCBITaxon.parseOtherNames( ...
                '<Taxon><ScientificName>x</ScientificName></Taxon>'), {});
            testCase.verifyEqual(ndi.ontology.NCBITaxon.parseOtherNames( ...
                ['<OtherNames><Name><ClassCDE>authority</ClassCDE>' ...
                '<DispName>x Smith, 1900</DispName></Name></OtherNames>']), {});
        end

    end % methods (Test)

end % classdef
